### ISSUE TITLE
Error with Tidal -> Apple music

### ISSUE THREAD

**Issue by JamyGolden** [Lytes/sound-tunnel#3]
Hi @Lytes, I tried using this to transfer playlists from Tidal -> Apple Music. Things authenticated correctly on both apps it seems, but there was still an error. I also got the same error when I specified an individual playlist. Any ideas what the issue is?

```sh
❯ python3 main.py -s tidal -d apple -A
HTTP error on 401
Visit https://link.tidal.com/FMJGI to log in, the code will expire in 300 seconds
[+] Tidal: Successfully Authenticated
[+] Apple: Successfully Authenticated
Traceback (most recent call last):
  File "/home/user/work/sound-tunnel/main.py", line 157, in <module>
    main()
  File "/home/user/work/sound-tunnel/main.py", line 138, in main
    tunnel(playlist, args.source, args.destination, core_sessions)
  File "/home/user/work/sound-tunnel/main.py", line 45, in tunnel
    playlist_info = get_tidal_playlist_content(tidal, source_playlist_id)
  File "/home/user/work/sound-tunnel/src/tidalfuncs.py", line 47, in get_tidal_playlist_content
    playlist_content = tidal.get_playlist_items(source_id)
AttributeError: 'Session' object has no attribute 'get_playlist_items'
```

**System:**

Python version: `Python 3.10.12`
OS: `Pop!_OS 22.04 LTS`

**Comment by Lytes** [comment]
I'll take a look.

**Comment by Lytes** [comment]
Issue fixed in

https://github.com/Lytes/sound-tunnel/commit/b47c2892ead71fd75635659cfee99050e90db3a7
